# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a parameter of beta distribution
#' @param b parameter of beta distribution
#' @param m parameter of distribution
#' @return a random sample of size \code{n}
#' @export
gib_chain_rcpp <- function(a, b, m) {
    .Call('_StatComp21036_gib_chain_rcpp', PACKAGE = 'StatComp21036', a, b, m)
}

